### ISSUE TITLE
Last steps for inspec.io launch

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1114]
- [x] try to build locally to dist dir
- [x] rake file for build process to gh-pages https://github.com/chef/inspec/pull/1132
- [x] add CNAME https://github.com/chef/inspec/pull/1132
- [x] build online demo in www build process https://github.com/chef/inspec/pull/1139
- [x] do the inspec.io thing (redirect/... with @cwebberOps )
- [x] https://chefio.atlassian.net/browse/CIA-1099 draft the downloads page
- [x] readme.md in www
- [x] overview page
- [x] docs on site (styling)
- [x] docs on site => https://github.com/chef/inspec/issues/1119

-- bugfixes

Thank you for reporting @chris-rock 
- [ ] demo doesn't work from docs sites (top and inline) (found the bug: relative paths bite us here...)
- [x] css in search https://github.com/chef/inspec/issues/1114#issuecomment-249525984 https://github.com/chef/inspec/pull/1157
- [x] button horizontal positioning https://github.com/chef/inspec/issues/1114#issuecomment-249526810 https://github.com/chef/inspec/pull/1161
- [x] links on community page don't work https://github.com/chef/inspec/pull/1162
- [x] scrolling on online demo when entering commands 
- [x] online demo code snipped coloring (slightly darker text on slightly lighter background is bad) https://github.com/chef/inspec/issues/1114#issuecomment-249527507
- [x] update generator script #1159
- [x] https://chefio.atlassian.net/browse/CIA-1099 download page has link

-- stretch
- [ ] lorem ipsum for guiding principles
- [ ] backup last N sites to be restore

**Comment by chris-rock** [comment]
also the footer linking to unavailable pages

**Comment by arlimus** [comment]
ping @cwebberOps

**Comment by chris-rock** [comment]
a strange line above the searchbar
<img width="249" alt="screen shot 2016-09-26 at 11 45 47 am" src="https://cloud.githubusercontent.com/assets/1178413/18829927/d0fb839c-83de-11e6-85cd-c85a4c6f5700.png">

**Comment by chris-rock** [comment]
Buttons should be on the same horizontal line
<img width="907" alt="screen shot 2016-09-26 at 11 49 41 am" src="https://cloud.githubusercontent.com/assets/1178413/18830063/5861b86a-83df-11e6-9db6-f2efce0254ac.png">

**Comment by chris-rock** [comment]
Commands should use the color `color: #87cefa;`
<img width="1010" alt="screen shot 2016-09-26 at 11 51 20 am" src="https://cloud.githubusercontent.com/assets/1178413/18830161/d8e62bb0-83df-11e6-94b8-004f9f4de005.png">
and scrolling does not work as expected
