### ISSUE TITLE
Remove deprecations for InSpec 2.0

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1728]
This issue will serve as a checklist of items we need to remove from the codebase as part of the InSpec 2.0 release. Since these are currently deprecations, they will become expected errors, etc. with InSpec 2.0. Therefore, these should not be removed until right before the 2.0 release.

InSpec core:

- [x] #1723: `assignment_re` and `key_vals` config keys
- [x] #2339: remove exec `--cache` flag
- [x] #2397: remove lowercase os name protection
- [x] remove `resource_skipped` (replaced by `resource_exception_message`)

InSpec matchers:

* [x] `contain_legacy_plus`, should have been removed in 1.0
* [x] `contain_match`, should have been removed in 1.0
* [ ] `contain_duplicates`, should have been removed in 1.0
* [x] `with_version` in favor of `its('version')`
* [x] `belong_to_group` in favor of `its('groups') { should include(...) }`
* [x] `belong_to_primary_group` in favor of `its('group') { should eq ... }`
* [x] `contain` in favor of `its('content') { should include(...) }`
* [x] `with_version` in favor of `its('version') { should eq ... }`

InSpec resources:

* `passwd`
  * [ ] `passwd.count`, should have been removed in 1.0
  * [ ] `passwd.usernames`, should have been removed in 1.0
  * [ ] `passwd.username`, should have been removed in 1.0
  * [ ] `passwd.uid`, should have been removed in 1.0
* `auditd_rules` - replaced with `auditd` in #2133

**Comment by arlimus** [comment]
Thank you for keeping track of this @adamleff !!

**Comment by arlimus** [comment]
Added a few more.

**Comment by arlimus** [comment]
Some of these might be old and we can use create discussion threads if needed :)

**Comment by username-is-already-taken2** [comment]
Hi there, 

I would like to find a way of helping you with getting inspec to 2.0.  May I ask how do you manage the PR's for the release?  For something like removing passwd.count from the passwd resource.  If I was to raise a PR that removes that functionailty do you store these up or apply them to a 2.0 branch that you raise to master at some point?

Never been involved with something like this, happy to chip away at the dockey work in the evening if it helps.

Gary

**Comment by adamleff** [comment]
Hi, @username-is-already-taken2! We greatly appreciate your willingness to help!

This kind of problem is always tricky... no matter what approach, we're going to be dealing with merge conflicts, etc.  So here's what we agreed to do a while back:

 * there is a branch called `release-2.0` where we will store any 2.0-related items that should NOT be released in a 1.x release
 * Any PRs that address 2.0-related features should target that branch
 * The InSpec maintainers will start doing weekly merges from `master` to keep the `release-2.0` branch updated (I'll probably do it on Thursdays after I do weekly the InSpec release)
 * When it's time for the 2.0 release, we'll merge `release-2.0` into `master` and bump the version.

So, if you want to chip away at some of that, please feel free! Also, there's a bunch of issues labeled `Type: Bug` that could use some help too!

Thanks again!

**Comment by jerryaldrichiii** [comment]
For posterity this should also do the following:
  - Removes `login_automate` https://github.com/chef/inspec/issues/2154
  - Removes `resource_skipped` in favor of `resource_exception_message`
