### ISSUE TITLE
Post-InSpec 3.0 Plugin system features

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3317]
### 🎛 Description

🙋 feature request

This ticket is to collect Plugin features that we plan to (intentionally) omit from the InSpec v3 release.  We may split these into individual issues as needed.

* [x] Trying to do a gemfile install with an update is an error if the file version matches the installed version
* [x] Prevent removing a gem if it will lead to unsolveable dependencies
* [x] reject list facility, used for search and install to block things like `inspec-core` and `train-tax-calculator`, which should not be treated as plugins. 

I'm not sure #3742 should be closed - it looks like the tests make just be skipping, not actually installing the plugins.

### 🌍 InSpec and Platform Version

3.x

Refs #3089

**Comment by kekaichinose** [comment]
Will leave the issues in the backlog for us to address as-necessary, but will actually close this epic as it is tied to InSpec 3.0 which has already launched some time back.
