### ISSUE TITLE
Convert old plugins and functionality to V2 plugins (reporters, fetchers, secrets, etc)

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#3638]
### 🎛 Description

🙋 feature request

We currently have a mix of v0, v1, and v2 plugins internally in InSpec.  v0 is total chaos; v1 is undocumented and unstable; and v2 is our publicly declared plugin API. By converting the plugin types, we empower passionate community members and partners to customize InSpec for their environment.

To convert the old functionality, we need to define plugin types, then convert each old plugin.

- [x] CLI commands
- [x] Attribute Providers (underway on #3666)
- [ ] Resources
- [ ] Reporters (tracked on #3667)
- [ ] Fetchers
- [ ] Source Readers
- [ ] Remove support for v1 plugins

**Comment by jquick** [comment]
This needs to be divided out into sub tasks. We need to decide which ones we want/need. I think it would be roughly Medium size for each plugin time we are looking to convert.
