### ISSUE TITLE
Rename attributes to inputs

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3802]
### 🎛 Description

🙋 feature request

Per #3748, InSpec `attributes` will be renamed to be InSpec `inputs` to avoid confusion with Chef attributes.

Thusly:

 * [x] Rename test files - #3796 
 * [x] Rename code files - #3803
    * [x] Check for external inclusion from other projects
 * [x] Add deprecation group - #3805
 * [x] Rename classes and non-DSL methods #3811
 * [x] Decide what to do about DEFAULT_ATTRIBUTE #3832 
 * [ ] Create aliases for user-visible features, with deprecation hooks
   * [x] DSL methods #3853
   * [x] --attrs #3855
   * [ ] audit cookbook `default['audit']['attributes'] https://github.com/chef-cookbooks/audit/issues/360
   * [x] kitchen-inspec `verifier`/`attributes` option https://github.com/inspec/kitchen-inspec/issues/224
   * [x] Metadata attributes #3854
 * [x] Update docs to mention 'inputs' in addition to attributes #3880
 * [ ] Update examples and code generator templates #3878
 * [ ] Update Learn Chef materials #3881
 * [ ] Alter `attributes` field in output of `inspec schema` (major version + 1)
 * [ ] Update json reporter to use inputs
 * [ ] Enable deprecation warnings (major version + 1)
 * [ ] Update docs to remove mention of attributes (major version + 2)
 * [ ] Remove aliases (attributes stop working) (major version + 3)

**Comment by luckylittle** [comment]
I use `inspec 4.16.0` and i've got this: `input('cis_level', value: 2)` in my controls, but it is complaining that: `WARN: Input 'cis_level' does not have a value. Use --input-file to provide a value for 'cis_level' or specify a value with attribute('cis_level', value: 'somevalue', ...)`. Which one should be used then? `input` or `attribute`?

**Comment by clintoncwolfe** [comment]
We'll address your issue on #4445 - thanks @luckylittle
