### ISSUE TITLE
Externalize AWS resources, use AWS SDK 3

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3822]
### 🎛 Description

This is an implementation issue to track work related to pushing the AWS resources out to a resource pack, and using AWS SDK v3.

Obsoletes #2571 
Obsoletes https://github.com/inspec/train/issues/350

 * [x] Revive https://github.com/inspec/inspec-aws - thanks to @skpaterson!
 * [x] Create inspec 4 branch (See 4-stable)
 * [x] Release train 2.0 with no AWS deps
 * [x] Release train-aws 0.1.0 with aws-sdk-3 deps
 * [x] On 4-stable branch, rely on train ~> 2.0 and train-aws ~> 0.1
 * [x] On 4-stable branch to retain `aws_` resources, but now against v3 #3823
 * [x] On 3-stable/master branch, add deprecation hooks in `ignore` mode #3824
 * [x] Migrate open PRs and issues to https://github.com/inspec/inspec-aws
 * [ ] On 4-stable branch, set deprecation group to warn
 * [x] On 4-stable branch, update `inspec init --platform aws` to generate profiles with a `depends` on the resource pack - #3831
 * [ ] On 4-stable branch, update docs/platforms

**Comment by skpaterson** [comment]
Thanks for this @clintoncwolfe ! Couple of updates:
* Migrate open PRs and issues to https://github.com/inspec/inspec-aws  - we're currently working on open PRs and targeting early next week for transferring/closing out AWS related issues
* On 4-stable branch, update `inspec init --platform aws` to generate profiles with a `depends` on the resource pack - see #3831

**Comment by btm** [comment]
@clintoncwolfe can this be closed now?

**Comment by clintoncwolfe** [comment]
Yes!
