### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by miah** [inspec/inspec#3846]
The InSpec team would like to gather, and report on details regarding usage to help make better decisions about how InSpec is being used.

Data we might want to collect:
 - Runtime environment (OS, Ruby Version)
 - Target(s) (unix, windows, network device, http, database, etc)
 - Runtime environment specs (memory, architecture, ipv(4,6)
 - InSpec features used (attributes, profiles, resources, plugins, custom resources, deprecations)

This is an Epic, so here is the task breakdown:

 - [ ] Write report locally
 - - [ ] Collect local environment details
 - - [ ] Collect remote environment details
 - - [ ] Collect deprecation details
 - [x] Opt-in / Opt-out
 - [ ] Send report to telemetry endpoint
 - - [ ] Fast-fail without network access / airgap
 - - [ ] Ability to set different endpoints
 - - [ ] Internal Telemetry Dashboard
 - [ ] Document Telemetry in docs/dev

**Comment by clintoncwolfe** [comment]
Suggested data point - Ruby exceptions https://github.com/inspec/inspec/pull/3903#issuecomment-475866638

**Comment by aaronlippold** [comment]
So does this encapsulate also the open issue we have with pass through metadata from the user as well as the discussion around the ahi resource and the expansion of the reporters to collect and report on this type of information?

**Comment by aaronlippold** [comment]
I don't want us to diverge too much with those three different open items if we're going to hopefully centralize them here in a consolidated conversation.

**Comment by clintoncwolfe** [comment]
Telemetry is about optionally collecting runtime data and sending it to Chef, for use in future product decisions.

If you want to capture network identifying data (as on #3869) and include it in the results of the run, with the intended recipient being the user, then you want a Reporter.
