### ISSUE TITLE
Ruby 2.6 compatibility

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3950]
### 🎛 Description

InSpec currently fails tests on 2.6 . Before adding 2.6 to the test matrix, fix any issues that will cause it to fail.

### 🌍 InSpec and Platform Version

3.9.3

### 🤔 Replication Case

```
rbenv local 2.6.1 # or whatever you use
bundle exec rake test
bundle exec rake test:functional
```

### 💁 Known Issues

* [x] Plugin tests fail under 2.6 #3978
* [x] MSSQL header parsing, #3971 
* [x] ss parsing code for IPv6 #3962 (may be platform-specific to archlinux)
