### ISSUE TITLE
Support InSpec on Habitat for Windows

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4424]
## User Story
As an enterprise user of Chef InSpec, I need a Habitat package for Windows to get started with Chef's content easily and in a future-proofed manner using the Effortless Infrastructure deployment model.

## Acceptance Criteria
Habitat builds of Chef InSpec client are:

 - [x] built in parallel of the omnibus builds
 - [x] cause the whole pipeline to appropriately fail if they fail
 - [x] are promoted in parallel with the omnibus builds
 - [x] run the same test suite as the omnibus packages
