### ISSUE TITLE
Numerous new resource requests

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#563]
@aaronlippold reported via [gitter](https://gitter.im/chef/inspec)

Missing documentation:
- [x] tags, refs #562
- [ ] update all the examples in the subpages to be with the current lang and style. #562
- [ ] Where are the man pages - what if I want to RTFM.

Suggested InSpec Resources
- [ ] selinux : For enabling/disabling/checking status #534
- [ ] selinux_rule : ... #534
- [ ] apparmor : same as selinux
- [ ] apparmor_rule: ...
- [ ] login_defs : for hacking on login_defs without sed/grep/awk
- [ ] login_defs_module
- [ ] password_config: For hacking on each of the distros password setup / rules
- [ ] support for crack_lib.so and pam_pwquality.so, etc.
- [ ] firewall

**Comment by aaronlippold** [comment]
For Suggested Resources:
- sudoers 
  - enable disable
  - with_pass , without_pass
  - groups
    etc.

**Comment by chris-rock** [comment]
Proposed additions by @aaronlippold in Gitter to add flexible query/check 
- [ ] profile tag/element query - show me all the controls that have this tag, over impact .5 etc.
- [ ] profile ‘structure’ enforcement, i.e. profile X controles require elements x,y,z’, need control tags a,b,c which leads to the ‘compiance coverage’ we were talking about. ( i.e. For CIS you could have a list of all the contols and then ensure that the profile enforces them. Also - you could mark some controls as ‘inactive’ for a less restrictive ‘dev’ overlay concept. - The Overlay concept is very important for supporting [RMF](http://csrc.nist.gov/groups/SMA/fisma/framework.html) for example. also see #564
- [ ] With a and b should come much better reporting both on the console and on the web. 
- [ ] a minimal signature of the profile. Also raised at [feedback.chef.io](https://feedback.chef.io/forums/330231-compliance-product-feedback/suggestions/13114317-signed-profiles-and-signed-results-with-a-known-in)

**Comment by kdshah1** [comment]
Adding to suggested Resources: ip6tables

**Comment by fcaviggia** [comment]
Adding to suggested Resources: firewalld (firewall-cmd)

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
